language: c

env:
  matrix:
    - "LUA=lua5.1 EVLOOP=epoll"
    - "LUA=lua5.1 EVLOOP=select"

install:
  - "sudo apt-get install -yq $LUA $lib$LUA-0-dev python-pexpect scons"
  - "./tests/netsnmp_build.sh"

script:
  - "scons --with-agentx --evloop=$EVLOOP"
  - "sudo SYS_LUA_PATH=`$LUA -e 'print(package.path)'` LUA=$LUA python ./tests/test_all.py"

after_success:

after_failure:
  - "cat config.log"
  - "cat tests/test.log"
